### ISSUE TITLE
Where is the online demo for Chapter 2?

### ISSUE THREAD

**Issue by silverbucket** [fycth/WebRTC-Blueprints#1]
Hello, I own a copy of your book and have had trouble getting the examples running on my system, but I read in the README here that the demos are also up and running on your website, however I cannot locate them. Do you have a link?

**Comment by fycth** [comment]
Hello Nick,

Demos:
chaper1: http://www.webrtcexample.com/WebRTC-Blueprints/demo/chapter1/
http://www.webrtcexample.com/WebRTC-Blueprints/demo/chapter3/

chapter2: http://www.webrtcexample.com/WebRTC-Blueprints/demo/chapter2/
http://www.webrtcexample.com/WebRTC-Blueprints/demo/chapter3/

chapter3: http://www.webrtcexample.com/WebRTC-Blueprints/demo/chapter3/

Unfortunately, code for the chapter 3 is outdated (they introduced some
changes in chrome so the code needs to be adapted to the changes now).

Feel free to contact me if you need any assistance.

Thanks

## 

Andrii Sergiienko
